### ISSUE TITLE
Tag for `mtl-2.3`

### ISSUE THREAD

**Issue by bgamari** [haskell/mtl#123]
It appears that there isn't yet a tag for the 2.3 release. Having one would be quite handy.

**Comment by andreasabel** [comment]
2.3 is broken, we are waiting for a patched version incorporating the following PR:
- #121

**Comment by ulysses4ever** [comment]
@kozross some timeline for a release with ExceptT restored would be very welcome, if possible. Thank you for volunteering to care for `mtl`!

**Comment by kozross** [comment]
@emilypi - any news on a new release?

**Comment by Bodigrim** [comment]
I'd appreciate to see a resolution to #119 before a new `mtl` release. Yet another month has passed, and neither tooling, nor migration guidance, nor public justification for the breakage have materialised.

**Comment by ulysses4ever** [comment]
A release with ExceptT put back would be an improvement over current state of things even if no guide materializes. Let’s not make perfect an enemy of the good.

**Comment by andreasabel** [comment]
2.3.1 has been released and a tag is present, so I think this issues can be closed.
