### ISSUE TITLE
Add support for transformers-0.5 release

### ISSUE THREAD

**Issue by hvr** [haskell/mtl#30]

**Comment by hvr** [comment]
somewhat related: ekmett/transformers-compat#11

**Comment by osa1** [comment]
:+1: , I can't use mtl in my plugins anymore because of this.

**Comment by osa1** [comment]
It seems like this is resolved.

**Comment by osa1** [comment]
Can we have a Hackage upload please?

**Comment by hvr** [comment]
@ekmett This is blocking a lot of packages from being tested with GHC 8.0 snapshots. And as it seems to be that in fact an upper-bound-relaxation is all that's needed, I've relaxed the upper bound on `transformers` for the existing `mtl` release: https://hackage.haskell.org/package/mtl-2.2.1/revisions/ -- if this is incorrect, please let me know

**Comment by ekmett** [comment]
@hvr thanks

**Comment by mitchty** [comment]
As a note, mtl still needs to have its bounds updated so that cabal-install can be bootstrapped with ghc 8.0, the hackage release still has ==0.4.* in its cabal bounds. Perhaps release an mtl candidate like cabal/cabal-install have so that bootstrap with ghc 8.0 can occur?

```
Registering Cabal-1.23.1.0...

Downloading mtl-2.2.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15391  100 15391    0     0  20845      0 --:--:-- --:--:-- --:--:-- 67209
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
Configuring mtl-2.2.1...
Setup: Encountered missing dependencies:
transformers ==0.4.*

Error during cabal-install bootstrap:
Configuring the mtl package failed.
```

**Comment by hvr** [comment]
@mitchty I'm confused... we edited https://hackage.haskell.org/package/mtl-2.2.1/revisions/ long ago... why doesn't that work for you?

**Comment by mitchty** [comment]
@hvr the cabal file on hackage which the bootstrap.sh script uses has the bound of ==0.4.* aka, this isn't going through cabal-install but bootstrapping cabal-install from scratch.

So once Setup.hs is run with the mtl.cabal with the old bounds bootstrap.sh fails.

And as a note this is to test out building cabal-install on a new architecture so not having an existing cabal is something I can't workaround as easily. >.<

I can just patch the bootstrap.sh script with an updated mtl package with the cabal file bounds relaxed like on hackage.

**Comment by hvr** [comment]
@mitchty if you look at https://github.com/haskell/cabal/blob/1.24/cabal-install/bootstrap.sh#L268-L298 the bootstrap script fetches the revised `mtl.cabal` file...

**Comment by mitchty** [comment]
That doesn't seem to be in the package in hackage however:
```
$ curl -L "https://hackage.haskell.org/package/mtl-2.2.1/mtl-2.2.1.tar.gz" | gzcat | tar xf - mtl-2.2.1/mtl.cabal
$ grep transformers mtl-2.2.1/mtl.cabal 
  build-depends: base < 6, transformers == 0.4.*
```

**Comment by mitchty** [comment]
Think I see the issue, ignore my comments. Thanks @hvr!

**Comment by robjhen** [comment]
There seems to be an inconsistency in the Hackage database between the following two files:

- [hackage.haskell.org/package/mtl-2.2.1/mtl.cabal](https://hackage.haskell.org/package/mtl-2.2.1/mtl.cabal)
- [hackage.haskell.org/package/mtl-2.2.1/src/mtl.cabal](https://hackage.haskell.org/package/mtl-2.2.1/src/mtl.cabal)

The first of these links is what you get when you click on 'package description': it contains the bound `transformers >= 0.4 && < 0.6`. The second is what you get when you actually download the package source: it contains the bound `transformers == 0.4.*`.

Is this a glitch - I assume these two files should be be the same?

**Comment by hvr** [comment]
@robjhen not a glitch, but rather the way `.cabal`-revisions work, c.f. http://hackage.haskell.org/package/mtl-2.2.1/revisions/

**Comment by RyanGlScott** [comment]
I believe this has been resolved, so closing.
