### ISSUE TITLE
Stricter Writer

### ISSUE THREAD

**Issue by minad** [haskell/mtl#38]
Hi,

I made the packages writer-cps-mtl and writer-transformers-mtl which implement a stricter writer monad transformer in continuation passing style as was discussed before on the Haskell mailing list etc
- http://hackage.haskell.org/package/writer-cps-mtl
- http://hackage.haskell.org/package/writer-cps-transformers

See also the current reddit discussion:
https://www.reddit.com/r/haskell/comments/50hf2s/stricter_writert_and_rwst_replacements/

Would you be interested in including this into mtl? If not it can also exist as a separate package, but I guess it would be nice to have a well-behaving writer around in the standard toolbox.

Daniel

**Comment by int-index** [comment]
@minad Thank you for `writer-cps-*` packages, I'll incorporate them into the next release of `ether` as the default implementation for `Writer`.

**Comment by minad** [comment]
It seems transformers pulled writer-cps-transformers, see https://hub.darcs.net/ross/transformers/patch/b6743fad9f5ce8a9e13f15320f7d2752330084e2

**Comment by RyanGlScott** [comment]
Assuming that these provide the same interface as the other `State`/`Writer` data types (which appears to be the case from a cursory glance, although I have not looked deeply), I'd happily accept a patch which adds `MonadState`/`MonadWriter` instances for these.

**Comment by minad** [comment]
As soon as the new transformers is released, you can pull the code from http://hackage.haskell.org/package/writer-cps-mtl. I can also prepare a patch. The same applies to the other writer-cps-* packages, providing orphan instances for exceptions, lens and mmorph.

**Comment by RyanGlScott** [comment]
I believe #67 implements this on `mtl`'s side, so closing. Please re-open if you disagree.
