### ISSUE TITLE
Make ((,) a) an instance of MonadWriter

### ISSUE THREAD

**Issue by tysonzero** [haskell/mtl#40]
instance Monoid w => MonadWriter w ((,) w) where
        writer = swap
        tell = flip (,) ()
        listen ~(w, a) = (w, (a, w))
        pass ~(w, ~(a, f)) = (f w, a)

It might be necessary to put in a bit of CPP as the Monad instance of `Monoid w => Monad ((,) w)` only came around in base version 4.9.0.0, but to me this still seems like a worthwhile addition with no significant downsides.

**Comment by Taneb** [comment]
As of 0faad02c392f97c806136806f924e47247b115c4 this has been added.
