### ISSUE TITLE
Add Monoid/Semigroup instances to ReaderT and possibly others

### ISSUE THREAD

**Issue by 3noch** [haskell/mtl#48]
`IO` now has these instances in `base` and it seems that most monads could/should have them now.

**Comment by 3noch** [comment]
https://mail.haskell.org/pipermail/haskell-cafe/2017-March/126605.html

**Comment by RyanGlScott** [comment]
For starters, this kind of request should be made in `transformers`, as `ReaderT` _et al._ aren't defined in `mtl`.

Also, that Haskell Café link you posted shows why this hasn't happened yet—there isn't a solid consensus on what the instances should be.

**Comment by 3noch** [comment]
>  this kind of request should be made in transformers

Unfortunately `transformers` is on darcsden which gives an error when I try to login... :/

But after seeing that conversation I agree this is not a good idea. At least now we have an issue for it. ;)

**Comment by RyanGlScott** [comment]
I mention this since the maintainer of `transformers` isn't going to find this page. You'd need to file an issue [here](https://hub.darcs.net/ross/transformers/issues) for him to notice.

**Comment by 3noch** [comment]
Thanks. I did try that first but it appeared to be down. It appears to be back up now.
