### ISSUE TITLE
Merge Control.Monad.Writer.CPS from writer-cps-mtl

### ISSUE THREAD

**Issue by taktoa** [haskell/mtl#63]
Currently `transformers` has a type called `Control.Monad.Trans.Writer.CPS.WriterT` that does not have accompanying `MonadWriter` / lifting instances in MTL. These instances are currently implemented as orphan instances in `writer-cps-mtl`. It should be possible to pretty much just copy over the modules defined in that package over to `mtl` to gain support.

**Comment by fishtreesugar** [comment]
related #38

**Comment by taktoa** [comment]
Ah, I will close in favor of that ticket
