### ISSUE TITLE
Re-export evalCont/evalContT?

### ISSUE THREAD

**Issue by endgame** [haskell/mtl#64]
These two functions are present in `transformers` but not `mtl`:

* `evalCont :: Cont r r -> r` -- The result of running a CPS computation with the identity as the final continuation.
* `evalContT :: Monad m => ContT r m r -> m r` -- The result of running a CPS computation with return as the final continuation.

Should they be re-exported? If so, I will prepare a PR.

**Comment by RyanGlScott** [comment]
I think it would make sense to re-export these, especially since we do so for other `eval`-prefixed functions elsewhere in `mtl` (e.g., `evalState`). A pull request would definitely be welcome.
