### ISSUE TITLE
Cut a new release of mtl

### ISSUE THREAD

**Issue by jkachmar** [haskell/mtl#69]
`mtl` now provides a number of useful, unreleased changes (among them instances for `Control.Monad.Trans.Writer.CPS` and `Control.Monad.RWS.CPS` which were introduced in `transformers-0.5.6.2`).

Can we get a new release of this library in time for GHC 8.10, or has that ship sailed?

**Comment by Ailrun** [comment]
Now GHC 8.10 is released. Is there any process on cutting a new release?

**Comment by chessai** [comment]
@hvr @RyanGlScott what is the process for cutting a new release of mtl? I'm happy to take over that responsibility but I need to make sure I'm doing everything right.

**Comment by cartazio** [comment]
last i checked, @ekmett  was maintainer, or am i way out of date?

**Comment by ekmett** [comment]
It is still me. I'd be open to accepting a new maintainer or co-maintainer, @chessai.

**Comment by chessai** [comment]
@ekmett I'm certainly interested. What is the process for cutting a new release? Are there any tickets we should consider resolving before one?

**Comment by Ailrun** [comment]
Any updates?

**Comment by vdukhovni** [comment]
It would sure be nice to see this merged, I've just had to jump though some extraneous hoops to wrap RWS.CPS in some code I'm working on, but with this merged I could just write `deriving instance MonadRWS` and be done...

**Comment by cartazio** [comment]
Chess has upload perms for hackage now and if more help is needed I’ve asked @Bodigrim to chip in on release engineering , since he has excellent taste!

**Comment by vdukhovni** [comment]
Good to know this is progressing...

**Comment by chessai** [comment]
The main issue is that I am not sure what needs to be done (in terms of
issues/PRs) before a release, if anything. We could do a release now and
work on the other stuff later, or we could work on them now and delay the
release. The balance between those two is what has kept me from inaction.

After we have made a decision, we need to take mtl master and build a lot
of its biggest reverse dependencies on hackage, and also base/ghc, against
it, to make sure we didn't cause mass breakage.

MTL upgrades already thrash binary caches. Avoiding mass breakage is
something that needs careful attention. @Bodigrim @cartazio maybe we could
do a video call or something to figure out our plan of attack? Anyone else
who wants to join in on this? Please let me know.

**Comment by phadej** [comment]
There is https://hackage.haskell.org/package/writer-cps-mtl-0.1.1.6/docs/Control-Monad-Writer-CPS.html package. And back then when we discussed with @RyanGlScott we decided that it's better to keep writer-cps compat stuff there.

I.e. not to make everything worse by migrating `writer-cps-mtl` users to `mtl`. It's PITA.

Remember, `mtl` is now distributed with GHC. One would like to avoid need for `mtl-compat` (which exists, but it's not owned by CLC afaik).

**Comment by phadej** [comment]
The above mentioned discussion is in https://github.com/ekmett/transformers-compat/issues/39

**Comment by cartazio** [comment]
@phadej  do you mean  `writer-cps-mtl` users to `mtl-compat`. or did you mean `mtl`?

**Comment by Ailrun** [comment]
@phadej, do you mean that mtl will never cut a new release?
I mean, this repository already contains codes related to Control.Monad.Writer.CPS, so if mtl ever cuts a new release, it will be a part of mtl, do I mistaken?

**Comment by cartazio** [comment]
I'm reasnoably confident its a typo reference to mtl-compat vs write-csp-mtl being a sibling compat? (does mtl-compat or transformers-compat note this anywhere?).

rather than about `mtl`

**Comment by vdukhovni** [comment]
My take is that when it is time to cut the next major release bump of `mtl`, it should include the (already committed) new instances, and at that point `writer-cps-mtl` can be updated to just reexport the new `mtl` module.  I would not want to see the orphan implementation in `writer-cps-mtl` as a long-term solution.

**Comment by phadej** [comment]
I’m saying that it’s easier to not migrate any new code to mtl as writer-cps-monad already provides the mtl instances for transformers / writer-cps-transformers.

Alternatively one should add CPS transformers to transformers-compat and instances to mtl AND transformers-compat.

Just check how complicated the transformers-compat setup is already:

https://hackage.haskell.org/package/transformers-compat-0.6.5/dependencies

So I ask that if anything is migrated from writer-cps packages to mtl / transformers-compat it’s done in coordinated and double and triple-checked. The coupling between base/transformers/mtl is unfortunate.

Alternatively:

I’d be in favor of removing mtl and text dependency from parsec, (the only thing forcing it them to be boot libs), so both text and mtl don’t need to be shipped with GHC and therefore could be easily reinstallable and left outside of CLC supervision.

Then mtl and text could be improved in its own pace without worries about breaking downstream as GHC won’t force an upgrade.

**Comment by ekmett** [comment]
I'm happy to donate `transformers-compat` to the CLC if that moves the needle. (I suspect it doesn't, much.)

I have a good deal of sympathy for "migrating is hard" arguments, but I'm not sure we should let that be a barrier to any attempt at further progress. `mtl` has sat basically unmodified for years, it has to be able to cut a release _somehow_. 

If the data type is in supplied in `transformers`, and the class is in `mtl`, then the instance should be in `mtl`. The current status quo is a rats' nest, requiring the user search flail around blindly searching hackage, and is a needless exception to everything else we supply.

I do believe any work here will need to coordinate with Ryan Scott, for `mtl-compat` reasons, though.

**Comment by Bodigrim** [comment]
> I’d be in favor of removing mtl and text dependency from parsec, (the only thing forcing it them to be boot libs), so both text and mtl don’t need to be shipped with GHC 

@phadej  This sounds like a good idea. Do you mean something like this: https://github.com/Bodigrim/parsec/commit/3e122d73dcfac06a3fda07de7e8b93d3e8235e3d?

**Comment by Kleidukos** [comment]
@Bodigrim @phadej @chessai Where are we standing on that topic?

**Comment by phadej** [comment]
I'm not the one who can decide about `mtl`, I just comment on the internet (too much).

**Comment by Bodigrim** [comment]
Neither am I.

**Comment by ekmett** [comment]
I'm happy to cede governance of the `mtl` to the CLC.

**Comment by emilypi** [comment]
I can cut a release if you add myself and @chessai as maintainers @ekmett

**Comment by vdukhovni** [comment]
> I can cut a release if you add myself and @chessai as maintainers @ekmett

That's probably the easy part.  Has a decision been made on the division of responsibilities between:
* mtl
* writer-cps-mtl
* mtl-compat
* transformers
* ...

There seems to be a coordination issue here that cuts across packages, that's the real obstacle...

**Comment by chessai** [comment]
Are we blocked on #81?

**Comment by cartazio** [comment]
I think viktor raises the right point. And I think the division of
responsibility should be the one that

A) avoids needlessly breaking preexisting code

B) ensures that future new code need only transformers mtl and
mtl/transformers-compat. (Any other compat package should just be a
reexport of compat stuff from there )

**Comment by vdukhovni** [comment]
FWIW, though it probably does not have to be stated, I don't know enough history, or have broad enough contact with the existing library ecosystem to suggest any particular strategy.  I hope that someone with the right expertise will be able to step forward and suggest a specific strategy that can achieve consensus.

**Comment by phadej** [comment]
I'd suggest the following:

- make `transformers-compat` be compat package *only* for `transformers`
- repurpose `mtl-compat` to be `mtl` *true* compat package
- make `writer-cps-transformers` use `transformers-compat`
- make `writer-cps-mtl` use `mtl-compat`

First two packages are maintaiend by Ryan Scott, who is usually very responsive. 
`writer-cps-*` packages are maintained by Daniel Mendler who seems to be active on GitHub (nick: @minad).

The current problem is that `transformers-compat` is a compat package
for **both** `transformers` and `mtl`. `mtl-compat` shims small additional bits.

This is non-trivial engineering task, but relatively straight-forward,
though needs careful execution.
(causing major versions for `transformers-compat` and `mtl-compat`).

The benefit is that dependency graph would be static.
Now it is dynamic, sometimes `transformers-compat` depends on `mtl` sometimes it doesn't.

The follow-up benefit is that evolution of both `transformers`
and `mtl` won't be hindered by no compatibility story.

**Comment by ekmett** [comment]
added you both to transformers-compat and mtl on hackage

**Comment by minad** [comment]
Is someone is interested in maintainer rights for the writer-cps-* compatibility packages? @phadej? This would help in avoiding such coordination issues.

**Comment by phadej** [comment]
@minad, perfectly would be the same people as for `transformers(-compat)` and `mtl(-compat)`, i.e. not me.

**Comment by minad** [comment]
Just to be very explicit, who should be added? I am sorry - I didn't follow the discussion recently. I just got your ping.

**Comment by Kleidukos** [comment]
The whole CLC

**Comment by Bodigrim** [comment]
@Kleidukos it is techically impossible 

@minad please grant access to https://hackage.haskell.org/user/chessai and https://hackage.haskell.org/user/topos

**Comment by minad** [comment]
@emilypi @chessai I added you to the maintainer group on hackage to various writer-cps-* packages. Furthermore I added you to the github repositories https://github.com/minad/writer-cps-transformers and https://github.com/minad/writer-cps-mtl. Please let me know if something else is needed.

**Comment by chessai** [comment]
> @emilypi @chessai I added you to the maintainer group on hackage of various writer-cps-* packages. Furthermore I added you to the github repositories https://github.com/minad/writer-cps-transformers and https://github.com/minad/writer-cps-mtl. Please let me know if something else is needed.

@minad could you please re-send my github invitations? They expired.

Furthermore, Emily and I have committed time coordinating to getting this all done next weekend.

**Comment by jkachmar** [comment]
Closed via a019ae8247d40fbbe3fc6bef7508cf10b0b6be73 🎉
