### ISSUE TITLE
Plans for ListT and ErrorT

### ISSUE THREAD

**Issue by fumieval** [haskell/mtl#75]
They are finally removed after several years of deprecation (https://hub.darcs.net/ross/transformers/patch/7c809b6f9db019ed761c971d10c86fa004f60d89). Is it OK to simply remove them from `mtl` as well? If so I can submit a PR.

**Comment by chessai** [comment]
Yes. I would accept a PR for this. Make sure you take care with the
relevant CPP.

**Comment by fumieval** [comment]
Created https://github.com/haskell/mtl/pull/76 

> Make sure you take care with the relevant CPP

Can you elaborate a bit? No existing CPP seems to be affected
