### ISSUE TITLE
Generic lifting of MonadCont

### ISSUE THREAD

**Issue by KingoftheHomeless** [haskell/mtl#77]
It's possible to define a `liftCallCC` for any `MonadTrans` as follows:
```haskell
liftCallCC :: (MonadTrans t, Monad (t m), Monad m)
           => CallCC m (t m a) b -> CallCC (t m) a b
liftCallCC callCC main = join . lift . callCC $ \exit ->
  return $ main (lift . exit . return)
```

This satisfies the [uniformity condition](https://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Signatures.html#t:CallCC) as long as you assume `callCC` is algebraic; that is,
```haskell
callCC (\exit -> f (g >=> exit) >>= g) = callCC f >>= g
```
Which should always be true, except perhaps for `StateT`'s instance of `MonadCont`, since that doesn't satisfy the uniformity condition.

I've sketched a proof [here.](https://gist.github.com/KingoftheHomeless/5927257cc7f6f8a2da685a2045dac204)

[This has been used in the wild by @ekmett in `free`.](https://hackage.haskell.org/package/free-5.1.3/docs/src/Control.Monad.Trans.Free.Church.html#line-164)

Given its usefulness for defining `MonadCont` instances for novel monad transformers, I feel the generic `liftCallCC` or some variant thereof should be added to `mtl` (or `transformers`).

**Comment by chessai** [comment]
Seems reasonable to me. Can @ekmett weigh in here?

**Comment by KingoftheHomeless** [comment]
Actually, my assumption that `callCC` is always algebraic is incorrect.
```haskell
> let cont = \b -> if b then return () else throwError  "bad"
> evalCont $ runExceptT $ callCC (\c -> c False `catchError` \_ -> c True) >>= cont
Left "bad"
> evalCont $ runExceptT $ callCC (\c' -> (\c -> c False `catchError` \_ -> c True) (cont >=> c') >>= cont)
Right ()
```
The proof doesn't need the complete power of `callCC` being algebraic, however. Only this:
```haskell
   join $ callCC (\exit -> return $ main (exit . return))
== callCC main
```
(which algebraicity implies).

I have a hard time imagining an implementation of `callCC` which doesn't satisfy this. `ContT`'s `callCC` certainly does, and any lifting of `callCC` using the `liftCallCC` I defined does too (I've updated the gist to show this).
