### ISSUE TITLE
Deprecate Error and ErrorList classes

### ISSUE THREAD

**Issue by chessai** [haskell/mtl#78]
The existence of these classes is extremely strange to me. I think now that ListT and ErrorT are being removed, these can be deprecated. What do others think? @haskell/core-libraries-committee 

Also, this needs a proper library mailing list proposal

**Comment by fumieval** [comment]
Aren't they removed altogether? https://hub.darcs.net/ross/transformers/patch/7c809b6f9db019ed761c971d10c86fa004f60d89

**Comment by chessai** [comment]
Got my wires crossed, sorry
